### PR TITLE
Smartling translations are updated for commit 6fbfb3db389a26cedfc4223fe9b8949a4dd1b34b from develop

### PR DESCRIPTION
**Pull request by bassrock**
Please review updates and merge this pull request

### CODE REVIEW

**Review by cyndichin — COMMENTED** [review]
While we are here, can we delete the other localizable files that contain "Home"? i.e. now we have two files for germany `de-DE` and `de.lproj` 

image

**Comment by bassrock** [comment]
oh. @cyndichin i think maybe i messed up the file paths?

**Comment by bassrock** [comment]
I'll wait for smartling to finish and then fix it up

**Comment by cyndichin** [comment]
> oh. @cyndichin i think maybe i messed up the file paths?

I think our original file paths were not using the proper names, so I'm okay to revert those and use what smartling gives us now.

**Pull request merged**
