### PR TITLE
feat(coverage): adding code coverage reports

### PR DESCRIPTION
**Pull request by bassrock**
## Summary
* Turns on xcode coverage
* Adds in Danger.systems to post code coverage of changed files to the pr comments
    *  Note: we can build more on danger later if we want.

## References 
* https://pocket.slack.com/archives/C01UH57EJKD/p1663186743065739

## Implementation Details
* This implements danger with swift which adds some dependencies.
* Note that code coverage is on for all targets, this is because for some reason Xcode won't generate code coverage  unless it we tell it all.

## PR Checklist:
- [ ] Added Unit / UI tests
- [x] Self Review (review, clean up, documentation, run tests)
- [x] Basic Self QA

### CODE REVIEW

**Comment by dskuza** [comment]
@bassrock Is there an example of what this output will look like? This PR somewhat ironically doesn't show anything.

**Comment by bassrock** [comment]
@dskuza funny enough there was, but it removed it because it was all successful. It will look like this. https://github.com/fastlane-community/danger-xcov

**Comment by dskuza** [comment]
@bassrock Cool, and this really only affects CI, right? (Looks like there's just a tiny bit added to `bitrise.yml`)

**Comment by bassrock** [comment]
@dskuza yea thats correct

**Review by dskuza — APPROVED** [review]
@bassrock I don't see why we _shouldn't_ do this, but it seems like it might be a good retro topic at some point (just to be on the same page).

**Pull request merged**
